### ISSUE TITLE
Can't easily start through docker

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia#1095]
### parachain-2105.Dockerfile
```yaml
FROM ghcr.io/darwinia-network/darwinia:pango-6021
COPY . /app
```
### docker-compose service
```yaml
  parachain-2105-0:
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - parachain-2105-0:/data
    build:
      context: .
      dockerfile: parachain-2105.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/pangolin-local-2105.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2105-0
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --alice
      - --node-key=14205e4908156b951a6ca7a74e4c12230ef3a6c274c2766f71a18ff79a663ef0
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --name=relaychain-alice
    environment:
      RUST_LOG: xcm=trace
    ulimits: *a1
```
### logs
```
output-parachain-2105-1-1  | 2023-04-10 11:08:45.242  INFO main sc_cli::runner: Darwinia
output-parachain-2105-1-1  | 2023-04-10 11:08:45.242  INFO main sc_cli::runner: ✌️  version 6.0.2-unknown
output-parachain-2105-1-1  | 2023-04-10 11:08:45.242  INFO main sc_cli::runner: ❤️  by Darwinia Network <hello@darwinia.network>, 2018-2023
output-parachain-2105-1-1  | 2023-04-10 11:08:45.242  INFO main sc_cli::runner: 📋 Chain specification: Pangolin2 Local
output-parachain-2105-1-1  | 2023-04-10 11:08:45.242  INFO main sc_cli::runner: 🏷  Node name: parachain-2105-1
output-parachain-2105-1-1  | 2023-04-10 11:08:45.242  INFO main sc_cli::runner: 👤 Role: AUTHORITY
output-parachain-2105-1-1  | 2023-04-10 11:08:45.242  INFO main sc_cli::runner: 💾 Database: RocksDb at /data/chains/pangolin2-local/db/full
output-parachain-2105-1-1  | 2023-04-10 11:08:45.242  INFO main sc_cli::runner: ⛓  Native runtime: Pangolin2-6021 (DarwiniaOfficialRust-0.tx0.au0)
output-parachain-2105-1-1  | 2023-04-10 11:08:45.518  WARN main sc_sysinfo::sysinfo: Failed to run the sequential write disk benchmark: failed to create a test file: No such file or directory (os error 2)
output-parachain-2105-1-1  | 2023-04-10 11:08:45.534  WARN main sc_sysinfo::sysinfo: Failed to run the random write disk benchmark: failed to create a test file: No such file or directory (os error 2)
output-parachain-2105-1-1  | Error: Service(Client(Backend("Failed to create RocksDB directory: `Os { code: 13, kind: PermissionDenied, message: \"Permission denied\" }`.")))
output-parachain-2105-1-1  | 2023-04-10 11:08:45.546  INFO main darwinia_staking: [pallet::staking] assembling new collators for new session 0 at #0
output-parachain-2105-1-1  | 2023-04-10 11:08:45.546  INFO main darwinia_staking: [pallet::staking] assembling new collators for new session 1 at #0
output-parachain-2105-1-1  | 2023-04-10 11:08:45.550  INFO main darwinia::command: Parachain id: Id(2105)
output-parachain-2105-1-1  | 2023-04-10 11:08:45.550  INFO main darwinia::command: Parachain Account: 5Ec4AhNxga1JYLioRBNxfRnovheDELVbZTRSnKMgvSVPvNcN
output-parachain-2105-1-1  | 2023-04-10 11:08:45.550  INFO main darwinia::command: Parachain genesis state: 0x000000000000000000000000000000000000000000000000000000000000000000099e71ed78205318e88dfa7e142a464ff42d1cf5c38a79bf6896d397d8b6118b03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400
output-parachain-2105-1-1  | 2023-04-10 11:08:45.550  INFO main darwinia::command: Is collating: yes
```
