### ISSUE TITLE
Invalid transaction when `session.newSession` is emitted

### ISSUE THREAD

**Issue by luispdm** [darwinia-network/darwinia#1631]
Hi, [Laos](https://github.com/freeverseio/laos) developer here. There's something I want to share here that you might be unaware of.

We've been investigating an issue in our parachain that causes transactions to be invalid occasionally. This happens when `session.newSession` is emitted.

The issue comes from this line of `pallet-session`: https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/session/src/lib.rs#L563. It's been reported in the polkadot-sdk repo https://github.com/paritytech/polkadot-sdk/issues/184 but it remains unresolved as of today.

We successfully reproduced the issue in your runtime using [Chopsticks](https://github.com/AcalaNetwork/chopsticks/) with the following modified configuration:
```yml
endpoint: wss://darwinia-rpc.dwellir.com
mock-signature-host: true
db: ./darwinia.db.sqlite
runtime-log-level: 5
port: 9999
block: 4759199

import-storage:
  System:
    Account:
      - - - "0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac"
        - providers: 1
          data:
            free: '1000000000000000000000'
```

Block `4759199` is the one immediately preceding the emission of `session.newSession`. For reference, this is the screenshot of the invalid transaction:
![darwinia-tx-invalid](https://github.com/user-attachments/assets/c8ee2714-49b5-49d6-a5cf-6cfd7fd2084b)

And this is the screenshot of the newly produced block:
![darwinia-no-remark-in-block](https://github.com/user-attachments/assets/2060ed6b-5f57-4c01-9787-73282d5e1f63)
As you can see, `system.remark` is not emitted.

[This](https://github.com/freeverseio/laos/issues/895) is the issue on our side, in case you want to keep track of it.

Thank you for your time.
