### ISSUE TITLE
Follow Substrate CI

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia#265]
**https://github.com/paritytech/substrate/blob/master/.gitlab-ci.yml**

---

**Cache Here**
```yml
variables:
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       100
  CARGO_HOME:                      "/ci-cache/${CI_PROJECT_NAME}/cargo/${CI_JOB_NAME}"
  SCCACHE_DIR:                     "/ci-cache/${CI_PROJECT_NAME}/sccache"
  CARGO_INCREMENTAL:               0
  CI_SERVER_NAME:                  "GitLab CI"
  DOCKER_OS:                       "debian:stretch"
  ARCH:                            "x86_64"
```
